### PR TITLE
Add slots for an arrow and clear button

### PR DESCRIPTION
**Pull request by dan3439**

### CODE REVIEW

**Comment by adamberecz** [comment]
Why do you need this? They can be customized via CSS. If you have a use case that CSS cannot cover, please share.

**Comment by dan3439** [comment]
In my case i need custom svg as an arrow that changes fill on opened select list. So i can't insert my svg into the arrow before content propery. Same case for a clear button.

**Comment by JayPalm** [comment]
I have a similar use case as @dan3439 and would find this useful if accepted!

**Comment by adamberecz** [comment]
Added this in `1.4.0`

**Comment by JayPalm** [comment]
> Added this in `1.4.0`

Awesome, thanks! Will try it out soon!

**Pull request closed without merging**
