### PR TITLE
Bugfix - async loading function called every time a data attribute changed

### PR DESCRIPTION
**Pull request by muhammedkaraoglu**
#266 resolveOnLoad - bugfix

I don't know if the change I made will cause any other problems. But I would appreciate it if you could quickly check and confirm this because that's how it works according to my tests.

### CODE REVIEW

**Comment by andreas83** [comment]
to me it looks like this don't fix the issue reported here #266

**Comment by muhammedkaraoglu** [comment]
It works fine according to my tests. Didn't it work for you? @andreas83

**Comment by andreas83** [comment]
@muhammedkaraoglu sadly not, i still see an async call on every keystroke, exactly like in my demo:
https://codesandbox.io/s/quizzical-danny-shgoy0?file=/src/App.vue

**Comment by muhammedkaraoglu** [comment]
@andreas83 You keep encountering this problem because the PR has not been approved yet. Please apply and test the change I made in your own project.

**Comment by andreas83** [comment]
don't think so, i made a fork of your repro (muhammedkaraoglu/multiselect)  and included it into my project, i also took a look inside the node_modules if your changes (https://github.com/muhammedkaraoglu/multiselect/commit/d3cab980403a763238622ad95cd0b290160f9920) are applied.

**Comment by adamberecz** [comment]
Thanks but this was not a fix actually, you just removed a feature which happens to fix your issue. I've released `2.5.6` with a patch for this.

**Pull request closed without merging**
